[python]
label = "Python"

    [[python.questions]]
    question     = "What is the US standard"
    answers      = ["NIST 800-14"]
    alternatives = ["NIST 800-12", "CIS", "1881"]

    [[python.questions]]
    question     = "stopping operation on country of unrest"
    answers      = ["Avoidance"]
    alternatives = ["continue", "CIS", "1881"]

    [[python.questions]]
    question     = "Dion Training’s offices utilize an open concept floor plan. They are concerned that a visitor might attempt to steal an external hard drive and carry it out of the building. To mitigate this risk, the security department has recommended installing security cameras that are clearly visible to both employees and visitors. What type of security control do these cameras represent?r"
    answers      = ["deterrent"]
    alternatives = ["compenseting", "correcting", "administrative"]

    [[python.questions]]
    question = "What's the purpose of the built-in zip() function"
    answers = ["To iterate over two or more sequences at the same time"]
    alternatives = [
        "To combine several strings into one",
        "To compress several files into one archive",
        "To get information from the user",
    ]

    [[python.questions]]
    question     = "What does dict.get(key) return if key isn't found in dict"
    answers      = ["None"]
    alternatives = ["key", "True", "False"]

    [[python.questions]]
    question = "How do you iterate over both the indices and elements in an iterable"
    answers = ["enumerate(iterable)"]
    alternatives = [
        "enumerate(iterable, start=1)",
        "range(iterable)",
        "range(iterable, start=1)",
    ]

    [[python.questions]]
    question = "What's the official name of the := operator"
    answers = ["Assignment expression"]
    alternatives = [
        "Named expression",
        "Walrus operator",
        "Colon equals operator",
    ]

    [[python.questions]]
    question = "What's one effect of calling random.seed(42)"
    answers = ["The random numbers are reproducible."]
    alternatives = [
        "The random numbers are more random.",
        "The computer clock is reset.",
        "The first random number is always 42.",
    ]

    [[python.questions]]
    question     = "Which version of Python is the first with TOML support built in"
    answers      = ["3.11"]
    alternatives = ["3.9", "3.10", "3.12"]

    [[python.questions]]
    question     = "suspend operation in country of unrest"
    answers      = ["python quiz.py", "python -m quiz"]
    alternatives = ["python quiz", "python -m quiz.py"]
    hint         = "One option uses the filename, and the other uses the module name."

    [[python.questions]]
    question     = "What's the name of the list-like data structure in TOML"
    answers      = ["Array"]
    alternatives = ["List", "Sequence", "Set"]

    [[python.questions]]
    question = "What's a PEP"
    answers = ["A Python Enhancement Proposal"]
    alternatives = [
        "A Pretty Exciting Policy",
        "A Preciously Evolved Python",
        "A Potentially Epic Prize",
    ]
    hint = "PEPs are used to evolve Python."
    explanation = """
    Python Enhancement Proposals (PEPs) are design documents that provide
    information to the Python community. PEPs are used to propose new features
    for the Python language, to collect community input on an issue, and to
    document design decisions made about the language.
    """

    [[python.questions]]
    question = "How can you add a docstring to a function"
    answers = [
        "By writing a string literal as the first statement in the function",
        "By assigning a string to the function's .__doc__ attribute",
    ]
    alternatives = [
        "By using the built-in @docstring decorator",
        "By returning a string from the function",
    ]
    hint = "They are parsed from your code and stored on the function object."
    explanation = """
    Docstrings document functions and other Python objects. A docstring is a
    string literal that occurs as the first statement in a module, function,
    class, or method definition. Such a docstring becomes the .__doc__ special
    attribute of that object. See PEP 257 for more information.

    There's no built-in @docstring decorator. Many functions naturally return
    strings. Such a feature can therefore not be used for docstrings.
    """

    [[python.questions]]
    question = "When was the first public version of Python released"
    answers = ["February 1991"]
    alternatives = ["January 1994", "October 2000", "December 2008"]
    hint = "The first public version was labeled version 0.9.0."
    explanation = """
    Guido van Rossum started work on Python in December 1989. He posted
    Python v0.9.0 to the alt.sources newsgroup in February 1991. Python
    reached version 1.0.0 in January 1994. The next major versions,
    Python 2.0 and Python 3.0, were released in October 2000 and December
    2008, respectively.
    """

[capitals]
label = "Capitals"

    [[capitals.questions]]
    question = "What's the capital of Norway"
    answers = ["Oslo"]
    hint = "Lars Onsager, Jens Stoltenberg, Trygve Lie, and Børge Ousland."
    alternatives = ["Stockholm", "Copenhagen", "Helsinki", "Reykjavik"]
    explanation = """
    Oslo was founded as a city in the 11th century and established as a
    trading place. It became the capital of Norway in 1299. The city was
    destroyed by a fire in 1624 and rebuilt as Christiania, named in honor
    of the reigning king. The city was renamed back to Oslo in 1925.
    """

    [[capitals.questions]]
    question = "What's the state capital of Texas, USA"
    answers = ["Austin"]
    alternatives = ["Harrisburg", "Houston", "Galveston", "Columbia"]
    hint = "SciPy is held there each year."
    explanation = """
    Austin is named in honor of Stephen F. Austin. It was purpose-built to
    be the capital of Texas and was incorporated in December 1839. Houston,
    Harrisburg, Columbia, and Galveston are all earlier capitals of Texas.
    """

[SecurityPlus]
label = "SecurityPlus"
    [[SecurityPlus.questions]]
    question     = "What is the US standard"
    answers      = ["NIST 800-14"]
    alternatives = ["NIST 800-12", "CIS", "1881"]

    [[SecurityPlus.questions]]
    question     = "stopping operation on country of unrest"
    answers      = ["Avoidance"]
    alternatives = ["continue", "CIS", "1881"]

    [[SecurityPlus.questions]]
    question     = "Dion Training’s offices utilize an open concept floor plan. They are concerned that a visitor might attempt to steal an external hard drive and carry it out of the building. To mitigate this risk, the security department has recommended installing security cameras that are clearly visible to both employees and visitors. What type of security control do these cameras represent?r"
    answers      = ["deterrent"]
    alternatives = ["compenseting", "correcting", "administrative"]
 
    [[SecurityPlus.questions]]
    question     = "A security analyst is concerned about critical vulnerabilities that have been detected on some applications running inside containers. Which of the following is theBEST remediation strategy?"
    answers      = ["Update the base container Image and redeploy the environment."]
    alternatives = ["Include the containers in the regular patching schedule for servers.", "Patch each running container individually and test the application.", "Update the host in which the containers are running."]

    [[SecurityPlus.questions]]
    question = "An organization has decided to purchase an insurance policy because a risk assessment determined that the cost to remediate the risk is greater than the five- year cost of the insurance policy. The organization is enabling risk:"
    answers  = ["transference"]
    alternatives = ["avoidance", "acceptance", "mitigation"]

    [[SecurityPlus.questions]]
    question = "A security analyst is receiving numerous alerts reporting that the response time of an internet-facing application has been degraded. However, the internal network performance was not degraded. Which of the following MOST likely explains this behavior?"
    answers =["DDoS attack"]
    alternatives = ["DNS poisoning", "MAC Flodding", "ARP poisioning"] 

    [[SecurityPlus.questions]]
    question = "a"
    answers =["DDoS attack"]
    alternatives = ["DNS poisoning", "MAC Flodding", "ARP poisioning"]

    [[SecurityPlus.questions]]
    question = "Which of the following statements BEST describes zero-day exploits?"
    answers =["A zero-day exploit is initially undetectable, and no patch for it exists."]
    alternatives = ["Zero-day exploits have their own scoring category in CVSS.", "When a zero-day exploit is discovered, the system cannot be protected by any means.", "Zero-day exploits have their own scoring category in CVSS."]

    [[SecurityPlus.questions]]
    question = "An organization wants to participate in threat intelligence information sharing with peer groups. Which of the following would MOST likely meet the organization's requirement?"
    answers =["Implement a TAXII server."]
    alternatives = ["Perform OSINT investigations", "Subscribe to threat intelligence feeds.", "Submit RFCs."]

    [[SecurityPlus.questions]]
    question = "A security analyst is designing the appropriate controls to limit unauthorized access to a physical site. The analyst has a directive to utilize the lowest possible budget. Which of the following would BEST meet the requirements?"
    answers =["Deterrent controls"]
    alternatives = ["Preventive controls", "Compensating controls", "Detective controls"]

    [[SecurityPlus.questions]]
    question = "The Chief Information Security Officer (CISO) has requested that a third-party vendor provide supporting documents that show proper controls are in place to protect customer data. Which of the following would be BEST for the third-party vendor to provide to the CISO?"
    answers =["SOC 2 Type 2 report"]
    alternatives = ["GDPR compliance attestation", "Cloud Security Alliance materials", "NIST RMF workbooks"]

    
    [[SecurityPlus.questions]]
    question = "Two organizations plan to collaborate on the evaluation of new SIEM solutions for their respective companies. A combined effort from both organizations' SOC teams would speed up the effort. Which of the following can be written to document this agreement?"
    answers = ["MOU"]
    alternatives = ["ISA", "SLA", "NDA"]

    [[SecurityPlus.questions]]
    question = "A security proposal was set up to track requests for remote access by creating a baseline of the users' common sign-in properties. When a baseline deviation is detected, an MFA challenge will be triggered. Which of the following should be configured in order to deploy the proposal?"
    answers = ["Context-aware authentication"]
    alternatives = ["Simultaneous authentication of equals", "Extensive authentication protocol", "Agentless network access control"]

    [[SecurityPlus.questions]]
    question = "In a rush to meet an end-of-year business goal, the IT department was told to implement a new business application. The security engineer reviews the attributes of the application and decides the time needed to perform due diligence is insufficient from a cybersecurity perspective. Which of the following BEST describes the security engineer's response?"
    answers = ["Risk acceptance"]
    alternatives = ["Risk tolerance", "Risk importance", "Risk appetite"]

    [[SecurityPlus.questions]]
    question = "Which of the following provides guidelines for the management and reduction of information security risk?"
    answers = ["NIST CSF"]
    alternatives =["CIS", "ISO", "PCI DSS"]

    [[SecurityPlus.questions]]
    question = "A security administrator needs a method to secure data in an environment that includes some form of checks so that the administrator can track any changes. Which of the following should the administrator set up to achieve this goal?"
    answers = ["FIM - File Integrity Monitor"]
    alternatives =["SPF", "GPO", "NAC"]

    [[SecurityPlus.questions]]
    question = "Which of the following can be used to calculate the total loss expected per year due to a threat targeting an asset?"
    answers = ["SLE x ARO"]
    alternatives =["EF x asset value", "ALE / SLE", "MTBF x impact"]
    explanation = """
    SLE stands for Single Loss Expectancy and is the expected monetary loss from a single incident. ARO stands for Annualized Rate of Occurrence and is the estimated number of times an incident is expected to occur in a year.
    """

    [[SecurityPlus.questions]]
    question = "During a forensic investigation, an analyst uses software to create a checksum of the affected subject's email file. Which of the following is the analyst practicing?"
    answers = ["Integrity"]
    alternatives =["Chain of custody", "Data recovery", "Non-repudiation"]
    explanation = """
    Creating a checksum of the affected subject's email file is an action that verifies the integrity of the file. In digital forensics, the process of creating a checksum involves generating a hash value (checksum) for a file. If the file remains unchanged, the hash value should remain consistent. If any alterations occur in the file, the hash value would differ, indicating a potential integrity issue.
    """

    [[SecurityPlus.questions]]
    question = "A security audit of an organization revealed that most of the IT staff members have domain administrator credentials and do not change the passwords regularly. Which of the following solutions should the security team propose to resolve the findings in the most complete way?"
    answers = ["Securing domain administrator credentials in a PAM vault and controlling access with role-based access control"]
    alternatives = ["Creating group policies to enforce password rotation on domain administrator credentials","Reviewing the domain administrator group, removing all unnecessary administrators, and rotating all passwords","Integrating the domain administrator's group with an IdP and requiring SSO with MFA for all access"]

    [[SecurityPlus.questions]]
    question = "Which of the following threat actors is most likely to use a high level of sophistication and potentially zero-day exploits to target organizations and systems?"
    answers = ["APT groups"]
    alternatives = ["Script kiddies", "Hacktivists", "Ethical hackers"]
    explanation = """
    APT (Advanced Persistent Threat) groups are most likely to use a high level of sophistication and potentially zero-day exploits to target organizations and systems. APTs are well-resourced and organized adversaries with specific objectives, often associated with nation-states or state-sponsored entities. They employ advanced techniques, including the development or use of zero-day vulnerabilities, to gain unauthorized access, maintain persistence, and exfiltrate sensitive information over an extended period.
    """

    [[SecurityPlus.questions]]
    question = "Which of the following describes the exploitation of an interactive process to gain access to restricted areas?"
    answers = ["Privilege escalation"]
    alternatives = ["Persistence", "Port scanning", "Pharming"]

    [[SecurityPlus.questions]]
    question = "A security analyst is assessing a new y developed web application by testing SQL injection, CSRF, and XML injection. Which of the follow ng frameworks should the analyst consider?"
    answers = ["OWASP"]
    alternatives = ["ISO", "NIST", "MITRE ATT&CK"]
    explanation = """
    The security analyst should consider OWASP (Open Web Application Security Project) framework. OWASP provides a comprehensive set of guidelines, tools, and techniques to help secure web applications. It also includes a top ten list of the most critical web application security risks, which includes SQL injection, CSRF, and XML injection.
    MITRE ATT&CK® is a globally-accessible knowledge base of adversary tactics and techniques based on real-world observations.
    """

[Kids]
label = "Kids"
    [[Kids.questions]]
    question     = "What is the 4*8"
    answers      = ["32"]
    alternatives = ["12", "36", "81"]  

    [[Kids.questions]]
    question     = "What is the 8*8"
    answers      = ["64"]
    alternatives = ["62", "22", "89"]  